### ISSUE TITLE
Is there any way to remove double quotes from the string

### ISSUE THREAD

**Issue by rohitsay89** [udp/json-builder#14]
I am trying to put a string value in the JSON format but do not want double quotes around the string value, is there any way to remove those double quotes ? 
All I want to do is to display a number in Hex format, as I am generating that number in form of a string I have to use the json_string_new method, which results in adding double quotes around that number. It would be great if you can show how to remove double quotes or if you have any dedicated function for displaying Hex values.

Thanks,
Rohit

**Comment by udp** [comment]
Sorry, this serializer follows the JSON specification which does not allow what you describe

http://json.org
