### ISSUE TITLE
Change include to use quotes instead of <>

### ISSUE THREAD

**Issue by cabeaulac** [udp/json-builder#5]
I'll do this and do a pull request now.
Use quotes to look in the local include path.

Change json-builder.h from

```
#include <json.h>
```

to

```
#include "json.h"
```

**Comment by cia48621793** [comment]
This is not necessary unless you are using MSVC as build platform

**Comment by udp** [comment]
Well... it really depends on how your build is set up.  If json-parser is installed as a separate library, angle brackets are correct.  json-builder does not bundle json-parser, so I don't think quotes would be correct in this case.

If json.h is located somewhere that your compiler is not looking for angle includes, can't you simply add a flag to look in the correct location?
